@startuml
title Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the site or bank-client")

System(MVPSystem, "Site or bank-client", "MVP site or bank-client")

System_Ext(api, "SMS provider API", "External API for sending sms")
System(bank, "Automation Bank System", "Internal automation bank system")
System(s3, "S3 storage", "S3 storage for Excel files")

Rel(user, MVPSystem, "Uses the system")

Rel(MVPSystem,api, "Send SMS with code")
Rel(MVPSystem,bank, "Registration of applications, obtaining a register of applications")
Rel(MVPSystem,s3, "Read Excel files with current deposit rates")

@enduml