@startuml
title Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A client of the bank")

System(IT_System, "MVP", "System for submitting applications for deposits")

Container_Boundary(IT_System, "Bank Standart System") {
  Container(WebApp, "Web Application", "ASP.NET, MS SQL", "Allows users to create and view applications for deposits")
  Container(Site, "Site", "React, PHP", "Allows users to create and view applications for deposits")
  Container(ABS, "Automation bank system", "Delphi, Oracle", "Bank operations")
  Container(S3, "S3 storage", "S3 storage", "Storage Excel files")
  Container(Kafka, "Kafka", "Kafka", "Message queue")
  Container(Redis, "Redis Cache", "Redis", "Caching layer for session data and applications information")
}

System_Ext(api, "SMS provider API", "External API for sending SMS")

Rel(user, WebApp, "Uses the system")
Rel(user, Site, "Uses the site")

Rel(WebApp, Kafka, "Send requests for create applications")
Rel(WebApp, S3, "Read Excel files for current rate of deposits")
Rel(Site, S3, "Read Excel files for current rate of deposits")
Rel(WebApp, ABS, "Send requests to get list of applications")

Rel(Site, Kafka, "Send requests for create applications")
Rel(Site, ABS, "Send requests to get list of applications")

Rel(ABS, Kafka, "Read messages to create applications")

Rel(WebApp,api,"Send SMS with code")
Rel(Site,api,"Send SMS with code")

Rel(WebApp, Redis, "Cache session data\nCache deposit applications", "TCP")
Rel(Site, Redis, "Cache session data\nCache deposit applications", "TCP")
@enduml