@startuml
title Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A client of the bank")
Person(operator, "Operator", "Operator of call-center")

System(CRM, "CRM", "CRM of bank")
System_Ext(CRM_ext, "CRM of external call-center")

System(s3, "S3 storage", "S3 storage for Excel files")

Rel(user, CRM, "Call to internal call-center")
Rel(user, CRM_ext, "Call to external call-center")

Rel(operator, CRM, "Recive calls and get information about rates")
Rel(operator, CRM_ext, "Recive calls and get information about rates")

Rel(CRM,s3, "Read Excel files with current deposit rates")
Rel(CRM_ext,s3, "Read Excel files with current deposit rates")

@enduml